### ISSUE TITLE
Bot not visible

### ISSUE THREAD

**Issue by Marc-Goritschnig** [researchstudio-sat/bot-skeleton#15]
I do not know the exact reason why, but when you start the Bot under the same name several times it is sometimes not visible under the new section even though it logs "Successfully registered as Matcher".

**Comment by quasarchimaere** [comment]
the new section is currently just showing atoms that have been created in the last 30 days but is limited to 200 for now, the list is retrieved from the won-node as rdf content and therefore is unsorted, so if there are more than 200 atoms present we only take the first 200 that are retrieved... we are trying to fix this for the hackathon

**Comment by quasarchimaere** [comment]
We updated the visible limit on our hackathon node so you should be able to find the bot-atoms in the whats new again.
